org.gradle.daemon=false
org.gradle.debug=false

minecraft_release=26.1.2
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neoforge_version=26.1.2.21-beta
neoforge_version_range=[26.1.2.21-beta,)
loader_version_range=[1,)

mod_id=extendedae
mod_name=ExtendedAE
mod_license=LGPL-3.0
mod_version=26.1-1.0.3-neoforge
mod_group_id=com.glodblock.github.extendedae
mod_authors=GlodBlock
mod_description=Add some QoL extended contents for AE2

use_Xei=jei
