org.gradle.jvmargs=-Xmx2G
org.gradle.caching=true

# Mod Info
modGroup = com.github.glodblock.eae
modId = extendedae
modName = ExtendedAE
modVersion = 1.12-0.0.1

# Minecraft Info
mcVersion = 1.12.2
userName = Developer

coreModPluginPath = com.github.glodblock.eae.coremod.EAECoreMod
generateTokenPath = com.github.glodblock.eae.EAETags