package com.glodblock.github.extendedae.common;

import appeng.api.stacks.AEFluidKey;
import appeng.api.stacks.AEItemKey;
import appeng.items.parts.PartItem;
import com.glodblock.github.extendedae.api.VoidMode;
import com.glodblock.github.extendedae.common.blocks.BlockBuddingEntro;
import com.glodblock.github.extendedae.common.blocks.BlockCaner;
import com.glodblock.github.extendedae.common.blocks.BlockCircuitCutter;
import com.glodblock.github.extendedae.common.blocks.BlockCrystalAssembler;
import com.glodblock.github.extendedae.common.blocks.BlockCrystalFixer;
import com.glodblock.github.extendedae.common.blocks.BlockEntroCluster;
import com.glodblock.github.extendedae.common.blocks.BlockExCharger;
import com.glodblock.github.extendedae.common.blocks.BlockExDrive;
import com.glodblock.github.extendedae.common.blocks.BlockExIOPort;
import com.glodblock.github.extendedae.common.blocks.BlockExInterface;
import com.glodblock.github.extendedae.common.blocks.BlockExMolecularAssembler;
import com.glodblock.github.extendedae.common.blocks.BlockExPatternProvider;
import com.glodblock.github.extendedae.common.blocks.BlockIngredientBuffer;
import com.glodblock.github.extendedae.common.blocks.BlockMascot;
import com.glodblock.github.extendedae.common.blocks.BlockOversizeInterface;
import com.glodblock.github.extendedae.common.blocks.BlockWirelessConnector;
import com.glodblock.github.extendedae.common.blocks.BlockWirelessHub;
import com.glodblock.github.extendedae.common.blocks.matrix.BlockAssemblerMatrixCrafter;
import com.glodblock.github.extendedae.common.blocks.matrix.BlockAssemblerMatrixFrame;
import com.glodblock.github.extendedae.common.blocks.matrix.BlockAssemblerMatrixGlass;
import com.glodblock.github.extendedae.common.blocks.matrix.BlockAssemblerMatrixPattern;
import com.glodblock.github.extendedae.common.blocks.matrix.BlockAssemblerMatrixSpeed;
import com.glodblock.github.extendedae.common.blocks.matrix.BlockAssemblerMatrixWall;
import com.glodblock.github.extendedae.common.items.CommonItem;
import com.glodblock.github.extendedae.common.items.ItemDriveUpgrade;
import com.glodblock.github.extendedae.common.items.ItemEntroSeed;
import com.glodblock.github.extendedae.common.items.ItemIOBusUpgrade;
import com.glodblock.github.extendedae.common.items.ItemInfinityCell;
import com.glodblock.github.extendedae.common.items.ItemInterfaceUpgrade;
import com.glodblock.github.extendedae.common.items.ItemMEPackingTape;
import com.glodblock.github.extendedae.common.items.ItemPackedDevice;
import com.glodblock.github.extendedae.common.items.ItemPatternAccessTerminalUpgrade;
import com.glodblock.github.extendedae.common.items.ItemPatternProviderUpgrade;
import com.glodblock.github.extendedae.common.items.ItemSmartAnnihilationPlane;
import com.glodblock.github.extendedae.common.items.ItemVoidCell;
import com.glodblock.github.extendedae.common.items.ItemWirelessConnectTool;
import com.glodblock.github.extendedae.common.items.ItemWirelessConnectorUpgrade;
import com.glodblock.github.extendedae.common.items.tools.ItemConfigModifier;
import com.glodblock.github.extendedae.common.items.tools.ItemPatternModifier;
import com.glodblock.github.extendedae.common.me.DirectionSet;
import com.glodblock.github.extendedae.common.parts.PartActiveFormationPlane;
import com.glodblock.github.extendedae.common.parts.PartExExportBus;
import com.glodblock.github.extendedae.common.parts.PartExImportBus;
import com.glodblock.github.extendedae.common.parts.PartExInterface;
import com.glodblock.github.extendedae.common.parts.PartExPatternAccessTerminal;
import com.glodblock.github.extendedae.common.parts.PartExPatternProvider;
import com.glodblock.github.extendedae.common.parts.PartModExportBus;
import com.glodblock.github.extendedae.common.parts.PartModStorageBus;
import com.glodblock.github.extendedae.common.parts.PartOversizeInterface;
import com.glodblock.github.extendedae.common.parts.PartPreciseExportBus;
import com.glodblock.github.extendedae.common.parts.PartPreciseStorageBus;
import com.glodblock.github.extendedae.common.parts.PartSmartAnnihilationPlane;
import com.glodblock.github.extendedae.common.parts.PartTagExportBus;
import com.glodblock.github.extendedae.common.parts.PartTagStorageBus;
import com.glodblock.github.extendedae.common.parts.PartThresholdExportBus;
import com.glodblock.github.extendedae.common.parts.PartThresholdLevelEmitter;
import com.glodblock.github.extendedae.common.tileentities.TileCaner;
import com.glodblock.github.extendedae.common.tileentities.TileCircuitCutter;
import com.glodblock.github.extendedae.common.tileentities.TileCrystalAssembler;
import com.glodblock.github.extendedae.common.tileentities.TileCrystalFixer;
import com.glodblock.github.extendedae.common.tileentities.TileExCharger;
import com.glodblock.github.extendedae.common.tileentities.TileExDrive;
import com.glodblock.github.extendedae.common.tileentities.TileExIOPort;
import com.glodblock.github.extendedae.common.tileentities.TileExInterface;
import com.glodblock.github.extendedae.common.tileentities.TileExMolecularAssembler;
import com.glodblock.github.extendedae.common.tileentities.TileExPatternProvider;
import com.glodblock.github.extendedae.common.tileentities.TileIngredientBuffer;
import com.glodblock.github.extendedae.common.tileentities.TileOversizeInterface;
import com.glodblock.github.extendedae.common.tileentities.TileWirelessConnector;
import com.glodblock.github.extendedae.common.tileentities.TileWirelessHub;
import com.glodblock.github.extendedae.common.tileentities.matrix.TileAssemblerMatrixCrafter;
import com.glodblock.github.extendedae.common.tileentities.matrix.TileAssemblerMatrixFrame;
import com.glodblock.github.extendedae.common.tileentities.matrix.TileAssemblerMatrixGlass;
import com.glodblock.github.extendedae.common.tileentities.matrix.TileAssemblerMatrixPattern;
import com.glodblock.github.extendedae.common.tileentities.matrix.TileAssemblerMatrixSpeed;
import com.glodblock.github.extendedae.common.tileentities.matrix.TileAssemblerMatrixWall;
import com.glodblock.github.extendedae.xmod.wt.ItemWirelessExPAT;
import com.glodblock.github.glodium.registry.defer.DeferredDataComponentType;
import com.glodblock.github.glodium.util.GlodCodecs;
import com.mojang.serialization.Codec;
import it.unimi.dsi.fastutil.Pair;
import net.minecraft.core.GlobalPos;
import net.minecraft.nbt.CompoundTag;
import net.minecraft.network.codec.ByteBufCodecs;
import net.minecraft.world.level.block.Block;
import net.minecraft.world.level.block.Blocks;
import net.minecraft.world.level.block.state.BlockBehaviour;
import net.minecraft.world.level.material.Fluids;
import net.neoforged.neoforge.registries.DeferredBlock;
import net.neoforged.neoforge.registries.DeferredItem;
import org.jetbrains.annotations.NotNull;

import static appeng.block.AEBaseBlock.metalProps;
import static appeng.block.AEBaseBlock.stoneProps;

public class EAESingletons {

    public static DeferredDataComponentType<Boolean> IS_PART;
    public static DeferredDataComponentType<ItemMEPackingTape.PartPackageData> TAPE_PART_DATA;
    public static DeferredDataComponentType<ItemMEPackingTape.TilePackageData> TAPE_TILE_DATA;
    public static DeferredDataComponentType<CompoundTag> STACK_TAG;
    public static DeferredDataComponentType<String> MOD_EXPRESS;
    public static DeferredDataComponentType<Pair<String, String>> TAG_EXPRESS;
    public static DeferredDataComponentType<CompoundTag> EXTRA_SETTING;
    public static DeferredDataComponentType<Pair<Long, Long>> THRESHOLD_DATA;
    public static DeferredDataComponentType<Pair<Long, GlobalPos>> WIRELESS_LOCATOR;
    public static DeferredDataComponentType<VoidMode> VOID_MODE;
    public static DeferredDataComponentType<Double> VOID_ENERGY;
    public static DeferredDataComponentType<ItemConfigModifier.ConfigSettings> MODIFIER_CONFIG_SETTINGS;
    public static DeferredDataComponentType<DirectionSet> DIRECTION_SET;

    public static DeferredItem<@NotNull CommonItem> ENTRO_CRYSTAL;
    public static DeferredItem<@NotNull ItemEntroSeed> ENTRO_SEED;
    public static DeferredItem<@NotNull CommonItem> ENTRO_DUST;
    public static DeferredItem<@NotNull CommonItem> ENTRO_INGOT;
    public static DeferredItem<@NotNull CommonItem> CONCURRENT_PROCESSOR;
    public static DeferredItem<@NotNull CommonItem> CONCURRENT_PROCESSOR_PRINT;
    public static DeferredItem<@NotNull CommonItem> CONCURRENT_PROCESSOR_PRESS;
    public static DeferredItem<@NotNull CommonItem> ENTRO_SHARD;
    public static DeferredBlock<@NotNull Block> ENTRO_BLOCK;
    public static DeferredBlock<@NotNull Block> MACHINE_FRAME;
    public static DeferredBlock<@NotNull BlockCrystalAssembler> CRYSTAL_ASSEMBLER;
    public static DeferredBlock<@NotNull BlockEntroCluster> ENTRO_BUD_SMALL;
    public static DeferredBlock<@NotNull BlockEntroCluster> ENTRO_BUD_MEDIUM;
    public static DeferredBlock<@NotNull BlockEntroCluster> ENTRO_BUD_LARGE;
    public static DeferredBlock<@NotNull BlockEntroCluster> ENTRO_CLUSTER;
    public static DeferredBlock<@NotNull BlockBuddingEntro> FULLY_ENTROIZED_FLUIX_BUDDING;
    public static DeferredBlock<@NotNull BlockBuddingEntro> MOSTLY_ENTROIZED_FLUIX_BUDDING;
    public static DeferredBlock<@NotNull BlockBuddingEntro> HALF_ENTROIZED_FLUIX_BUDDING;
    public static DeferredBlock<@NotNull BlockBuddingEntro> HARDLY_ENTROIZED_FLUIX_BUDDING;
    public static DeferredBlock<@NotNull BlockExPatternProvider> EX_PATTERN_PROVIDER;
    public static DeferredBlock<@NotNull Block> SILICON_BLOCK;
    public static DeferredItem<@NotNull PartItem<PartExPatternProvider>> EX_PATTERN_PROVIDER_PART;
    public static DeferredBlock<@NotNull BlockExInterface> EX_INTERFACE;
    public static DeferredItem<@NotNull PartItem<PartExInterface>> EX_INTERFACE_PART;
    public static DeferredItem<@NotNull ItemInfinityCell> INFINITY_WATER_CELL;
    public static DeferredItem<@NotNull ItemInfinityCell> INFINITY_COBBLESTONE_CELL;
    public static DeferredItem<@NotNull PartItem<PartExExportBus>> EX_EXPORT_BUS;
    public static DeferredItem<@NotNull PartItem<PartExImportBus>> EX_IMPORT_BUS;
    public static DeferredItem<@NotNull PartItem<PartExPatternAccessTerminal>> EX_PATTERN_TERMINAL;
    public static DeferredItem<@NotNull ItemMEPackingTape> PACKING_TAPE;
    public static DeferredItem<@NotNull ItemPackedDevice> PACKAGE;
    public static DeferredItem<@NotNull ItemPatternProviderUpgrade> PATTERN_PROVIDER_UPGRADE;
    public static DeferredItem<@NotNull ItemInterfaceUpgrade> INTERFACE_UPGRADE;
    public static DeferredItem<@NotNull ItemIOBusUpgrade> IO_BUS_UPGRADE;
    public static DeferredItem<@NotNull ItemPatternAccessTerminalUpgrade> PATTERN_UPGRADE;
    public static DeferredBlock<@NotNull BlockWirelessConnector> WIRELESS_CONNECTOR;
    public static DeferredItem<@NotNull ItemWirelessConnectTool> WIRELESS_TOOL;
    public static DeferredBlock<@NotNull BlockIngredientBuffer> INGREDIENT_BUFFER;
    public static DeferredBlock<@NotNull BlockExDrive> EX_DRIVE;
    public static DeferredItem<@NotNull ItemDriveUpgrade> DRIVE_UPGRADE;
    public static DeferredItem<@NotNull ItemPatternModifier> PATTERN_MODIFIER;
    public static DeferredBlock<@NotNull BlockExMolecularAssembler> EX_ASSEMBLER;
    public static DeferredBlock<@NotNull BlockExCharger> EX_CHARGER;
    public static DeferredBlock<@NotNull BlockCrystalFixer> CRYSTAL_FIXER;
    public static DeferredItem<@NotNull PartItem<PartTagStorageBus>> TAG_STORAGE_BUS;
    public static DeferredItem<@NotNull PartItem<PartTagExportBus>> TAG_EXPORT_BUS;
    public static DeferredItem<@NotNull PartItem<PartThresholdLevelEmitter>> THRESHOLD_LEVEL_EMITTER;
    public static DeferredItem<@NotNull PartItem<PartModStorageBus>> MOD_STORAGE_BUS;
    public static DeferredItem<@NotNull PartItem<PartModExportBus>> MOD_EXPORT_BUS;
    public static DeferredItem<@NotNull PartItem<PartActiveFormationPlane>> ACTIVE_FORMATION_PLANE;
    public static DeferredBlock<@NotNull BlockMascot> FISHBIG;
    public static DeferredBlock<@NotNull BlockMascot> MDDYUE;
    public static DeferredBlock<@NotNull BlockCaner> CANER;
    public static DeferredBlock<@NotNull BlockExIOPort> EX_IO_PORT;
    public static DeferredItem<@NotNull PartItem<PartPreciseExportBus>> PRECISE_EXPORT_BUS;
    public static DeferredItem<@NotNull ItemWirelessExPAT> WIRELESS_EX_PAT;
    public static DeferredItem<@NotNull PartItem<PartPreciseStorageBus>> PRECISE_STORAGE_BUS;
    public static DeferredItem<@NotNull PartItem<PartThresholdExportBus>> THRESHOLD_EXPORT_BUS;
    public static DeferredBlock<@NotNull BlockCircuitCutter> CIRCUIT_CUTTER;
    public static DeferredBlock<@NotNull BlockOversizeInterface> OVERSIZE_INTERFACE;
    public static DeferredItem<@NotNull PartItem<PartOversizeInterface>> OVERSIZE_INTERFACE_PART;
    public static DeferredBlock<@NotNull BlockAssemblerMatrixFrame> ASSEMBLER_MATRIX_FRAME;
    public static DeferredBlock<@NotNull BlockAssemblerMatrixWall> ASSEMBLER_MATRIX_WALL;
    public static DeferredBlock<@NotNull BlockAssemblerMatrixGlass> ASSEMBLER_MATRIX_GLASS;
    public static DeferredBlock<@NotNull BlockAssemblerMatrixPattern> ASSEMBLER_MATRIX_PATTERN;
    public static DeferredBlock<@NotNull BlockAssemblerMatrixCrafter> ASSEMBLER_MATRIX_CRAFTER;
    public static DeferredBlock<@NotNull BlockAssemblerMatrixSpeed> ASSEMBLER_MATRIX_SPEED;
    public static DeferredItem<@NotNull ItemVoidCell> VOID_CELL;
    public static DeferredItem<@NotNull CommonItem> QUARTZ_BLEND;
    public static DeferredItem<@NotNull ItemConfigModifier> CONFIG_MODIFIER;
    public static DeferredBlock<@NotNull BlockWirelessHub> WIRELESS_HUB;
    public static DeferredItem<@NotNull PartItem<PartSmartAnnihilationPlane>> SMART_ANNIHILATION_PLANE;
    public static DeferredItem<@NotNull ItemWirelessConnectorUpgrade> WIRELESS_CONNECTOR_UPGRADE;

    public static void init(EAERegistryHandler regHandler) {
        IS_PART = regHandler.comp("is_part", Codec.BOOL, ByteBufCodecs.BOOL);
        TAPE_PART_DATA = regHandler.comp("tape_part_data", ItemMEPackingTape.PartPackageData.CODEC, ItemMEPackingTape.PartPackageData.STREAM_CODEC);
        TAPE_TILE_DATA = regHandler.comp("tape_tile_data", ItemMEPackingTape.TilePackageData.CODEC, ItemMEPackingTape.TilePackageData.STREAM_CODEC);
        STACK_TAG = regHandler.comp("generic_nbt", CompoundTag.CODEC, GlodCodecs.NBT_STREAM_CODEC);
        MOD_EXPRESS = regHandler.comp("mod_express", Codec.STRING, ByteBufCodecs.STRING_UTF8);
        TAG_EXPRESS = regHandler.comp("tag_express", GlodCodecs.pair(Codec.STRING, Codec.STRING), GlodCodecs.pair(ByteBufCodecs.STRING_UTF8, ByteBufCodecs.STRING_UTF8));
        EXTRA_SETTING = regHandler.comp("extra_setting", CompoundTag.CODEC, GlodCodecs.NBT_STREAM_CODEC);
        THRESHOLD_DATA = regHandler.comp("threshold_data", GlodCodecs.pair(Codec.LONG, Codec.LONG), GlodCodecs.pair(ByteBufCodecs.VAR_LONG, ByteBufCodecs.VAR_LONG));
        WIRELESS_LOCATOR = regHandler.comp("wireless_locator", GlodCodecs.pair(Codec.LONG, GlobalPos.CODEC), GlodCodecs.pair(ByteBufCodecs.VAR_LONG, GlobalPos.STREAM_CODEC));
        VOID_MODE = regHandler.comp("void_mode", VoidMode.CODEC, VoidMode.STREAM_CODEC);
        VOID_ENERGY = regHandler.comp("void_energy", Codec.DOUBLE, ByteBufCodecs.DOUBLE);
        MODIFIER_CONFIG_SETTINGS = regHandler.comp("modifier_config_settings", ItemConfigModifier.ConfigSettings.CODEC, ItemConfigModifier.ConfigSettings.STREAM_CODEC);
        DIRECTION_SET = regHandler.comp("direction_set", DirectionSet.CODEC, DirectionSet.STREAM_CODEC);
        ENTRO_BUD_SMALL = regHandler.block("entro_cluster_small", prop -> new BlockEntroCluster(prop, 0, 3, 4));
        ENTRO_BUD_MEDIUM = regHandler.block("entro_cluster_medium", prop -> new BlockEntroCluster(prop, 1, 4, 3));
        ENTRO_BUD_LARGE = regHandler.block("entro_cluster_large", prop -> new BlockEntroCluster(prop, 2, 5, 3));
        ENTRO_CLUSTER = regHandler.block("entro_cluster", prop -> new BlockEntroCluster(prop, 3, 7, 3));
        FULLY_ENTROIZED_FLUIX_BUDDING = regHandler.block("entro_budding_fully", BlockBuddingEntro::new);
        MOSTLY_ENTROIZED_FLUIX_BUDDING = regHandler.block("entro_budding_mostly", BlockBuddingEntro::new);
        HALF_ENTROIZED_FLUIX_BUDDING = regHandler.block("entro_budding_half", BlockBuddingEntro::new);
        HARDLY_ENTROIZED_FLUIX_BUDDING = regHandler.block("entro_budding_hardly", BlockBuddingEntro::new);
        ENTRO_BLOCK = regHandler.block("entro_block", Block::new, stoneProps(Block.Properties.of()).strength(3, 8).requiresCorrectToolForDrops());
        MACHINE_FRAME = regHandler.block("machine_frame", Block::new, metalProps(Block.Properties.of()).requiresCorrectToolForDrops());
        CRYSTAL_ASSEMBLER = regHandler.block("crystal_assembler", BlockCrystalAssembler::new, TileCrystalAssembler.class, TileCrystalAssembler::new);
        EX_PATTERN_PROVIDER = regHandler.block("ex_pattern_provider", BlockExPatternProvider::new, TileExPatternProvider.class, TileExPatternProvider::new);
        EX_INTERFACE = regHandler.block("ex_interface", BlockExInterface::new, TileExInterface.class, TileExInterface::new);
        WIRELESS_CONNECTOR = regHandler.block("wireless_connect", BlockWirelessConnector::new, TileWirelessConnector.class, TileWirelessConnector::new);
        INGREDIENT_BUFFER = regHandler.block("ingredient_buffer", BlockIngredientBuffer::new, TileIngredientBuffer.class, TileIngredientBuffer::new);
        EX_DRIVE = regHandler.block("ex_drive", BlockExDrive::new, TileExDrive.class, TileExDrive::new);
        EX_ASSEMBLER = regHandler.block("ex_molecular_assembler", BlockExMolecularAssembler::new, TileExMolecularAssembler.class, TileExMolecularAssembler::new);
        EX_CHARGER = regHandler.block("ex_charger", BlockExCharger::new, TileExCharger.class, TileExCharger::new);
        CRYSTAL_FIXER = regHandler.block("crystal_fixer", BlockCrystalFixer::new, TileCrystalFixer.class, TileCrystalFixer::new);
        CANER = regHandler.block("caner", BlockCaner::new, TileCaner.class, TileCaner::new);
        EX_IO_PORT = regHandler.block("ex_io_port", BlockExIOPort::new, TileExIOPort.class, TileExIOPort::new);
        CIRCUIT_CUTTER = regHandler.block("circuit_cutter", BlockCircuitCutter::new, TileCircuitCutter.class, TileCircuitCutter::new);
        OVERSIZE_INTERFACE = regHandler.block("oversize_interface", BlockOversizeInterface::new, TileOversizeInterface.class, TileOversizeInterface::new);
        ASSEMBLER_MATRIX_FRAME = regHandler.block("assembler_matrix_frame", BlockAssemblerMatrixFrame::new, TileAssemblerMatrixFrame.class, TileAssemblerMatrixFrame::new);
        ASSEMBLER_MATRIX_WALL = regHandler.block("assembler_matrix_wall", BlockAssemblerMatrixWall::new, TileAssemblerMatrixWall.class, TileAssemblerMatrixWall::new);
        ASSEMBLER_MATRIX_GLASS = regHandler.block("assembler_matrix_glass", BlockAssemblerMatrixGlass::new, TileAssemblerMatrixGlass.class, TileAssemblerMatrixGlass::new);
        ASSEMBLER_MATRIX_PATTERN = regHandler.block("assembler_matrix_pattern", BlockAssemblerMatrixPattern::new, TileAssemblerMatrixPattern.class, TileAssemblerMatrixPattern::new);
        ASSEMBLER_MATRIX_CRAFTER = regHandler.block("assembler_matrix_crafter", BlockAssemblerMatrixCrafter::new, TileAssemblerMatrixCrafter.class, TileAssemblerMatrixCrafter::new);
        ASSEMBLER_MATRIX_SPEED = regHandler.block("assembler_matrix_speed", BlockAssemblerMatrixSpeed::new, TileAssemblerMatrixSpeed.class, TileAssemblerMatrixSpeed::new);
        WIRELESS_HUB = regHandler.block("wireless_hub", BlockWirelessHub::new, TileWirelessHub.class, TileWirelessHub::new);
        SILICON_BLOCK = regHandler.block("silicon_block", Block::new, metalProps(BlockBehaviour.Properties.of()).requiresCorrectToolForDrops());
        FISHBIG = regHandler.block("fishbig", BlockMascot::new);
        MDDYUE = regHandler.block("mddyue", BlockMascot::new);
        ENTRO_CRYSTAL = regHandler.item("entro_crystal", CommonItem::new);
        ENTRO_SEED = regHandler.item("entro_seed", ItemEntroSeed::new);
        ENTRO_DUST = regHandler.item("entro_dust", CommonItem::new);
        ENTRO_INGOT = regHandler.item("entro_ingot", CommonItem::new);
        CONCURRENT_PROCESSOR = regHandler.item("concurrent_processor", CommonItem::new);
        CONCURRENT_PROCESSOR_PRESS = regHandler.item("concurrent_processor_press", CommonItem::new);
        CONCURRENT_PROCESSOR_PRINT = regHandler.item("concurrent_processor_print", CommonItem::new);
        ENTRO_SHARD = regHandler.item("entro_shard", CommonItem::new);
        EX_PATTERN_PROVIDER_PART = regHandler.item("ex_pattern_provider_part", PartExPatternProvider.class, PartExPatternProvider::new);
        EX_INTERFACE_PART = regHandler.item("ex_interface_part", PartExInterface.class, PartExInterface::new);
        INFINITY_WATER_CELL = regHandler.item("infinity_water_cell", properties -> new ItemInfinityCell(() -> AEFluidKey.of(Fluids.WATER), properties));
        INFINITY_COBBLESTONE_CELL = regHandler.item("infinity_cobblestone_cell", properties -> new ItemInfinityCell(() -> AEItemKey.of(Blocks.COBBLESTONE), properties));
        EX_EXPORT_BUS = regHandler.item("ex_export_bus_part", PartExExportBus.class, PartExExportBus::new);
        EX_IMPORT_BUS = regHandler.item("ex_import_bus_part", PartExImportBus.class, PartExImportBus::new);
        EX_PATTERN_TERMINAL = regHandler.item("ex_pattern_access_part", PartExPatternAccessTerminal.class, PartExPatternAccessTerminal::new);
        PATTERN_PROVIDER_UPGRADE = regHandler.item("pattern_provider_upgrade", ItemPatternProviderUpgrade::new);
        INTERFACE_UPGRADE = regHandler.item("interface_upgrade", ItemInterfaceUpgrade::new);
        IO_BUS_UPGRADE = regHandler.item("io_bus_upgrade", ItemIOBusUpgrade::new);
        PATTERN_UPGRADE = regHandler.item("pattern_terminal_upgrade", ItemPatternAccessTerminalUpgrade::new);
        PACKING_TAPE = regHandler.item("me_packing_tape", ItemMEPackingTape::new);
        PACKAGE = regHandler.item("package", ItemPackedDevice::new);
        WIRELESS_TOOL = regHandler.item("wireless_tool", ItemWirelessConnectTool::new);
        DRIVE_UPGRADE = regHandler.item("drive_upgrade", ItemDriveUpgrade::new);
        PATTERN_MODIFIER = regHandler.item("pattern_modifier", ItemPatternModifier::new);
        TAG_STORAGE_BUS = regHandler.item("tag_storage_bus", PartTagStorageBus.class, PartTagStorageBus::new);
        TAG_EXPORT_BUS = regHandler.item("tag_export_bus", PartTagExportBus.class, PartTagExportBus::new);
        THRESHOLD_LEVEL_EMITTER = regHandler.item("threshold_level_emitter", PartThresholdLevelEmitter.class, PartThresholdLevelEmitter::new);
        MOD_STORAGE_BUS = regHandler.item("mod_storage_bus", PartModStorageBus.class, PartModStorageBus::new);
        MOD_EXPORT_BUS = regHandler.item("mod_export_bus", PartModExportBus.class, PartModExportBus::new);
        ACTIVE_FORMATION_PLANE = regHandler.item("active_formation_plane", PartActiveFormationPlane.class, PartActiveFormationPlane::new);
        PRECISE_EXPORT_BUS = regHandler.item("precise_export_bus", PartPreciseExportBus.class, PartPreciseExportBus::new);
        WIRELESS_EX_PAT = regHandler.item("wireless_ex_pat", ItemWirelessExPAT::new);
        PRECISE_STORAGE_BUS = regHandler.item("precise_storage_bus", PartPreciseStorageBus.class, PartPreciseStorageBus::new);
        THRESHOLD_EXPORT_BUS = regHandler.item("threshold_export_bus", PartThresholdExportBus.class, PartThresholdExportBus::new);
        OVERSIZE_INTERFACE_PART = regHandler.item("oversize_interface_part", PartOversizeInterface.class, PartOversizeInterface::new);
        VOID_CELL = regHandler.item("void_cell", ItemVoidCell::new);
        QUARTZ_BLEND = regHandler.item("quartz_blend", CommonItem::new);
        CONFIG_MODIFIER = regHandler.item("config_modifier", ItemConfigModifier::new);
        SMART_ANNIHILATION_PLANE = regHandler.item("smart_annihilation_plane", ItemSmartAnnihilationPlane::new);
        WIRELESS_CONNECTOR_UPGRADE = regHandler.item("wireless_connector_upgrade", ItemWirelessConnectorUpgrade::new);
    }

}
